# name: Run shell commands
# on: [push]

# jobs:
#  run-shell-command:
#   runs-on: ubuntu-latest
#   steps:
#   - name: Echo a string
#     run: echo "Hello this is a first job"


name: Platform BUILD
run-name: "#${{github.run_number}} - ${{github.event.inputs.environment}}"

on:
  workflow_dispatch:
    inputs:
      Environment:
         type: choice
         description: 'select emvironment'
         options:
         - dev
         - preprod


jobs:
 run-shell-command:
  runs-on: ubuntu-latest
  steps:
  - name: Echo a string
    run: echo "Hello this is a first job"
  - name: Run a pipeleine
    run: echo "This iakanvsdvmsdlkvm s"  