# name: Run shell commands
# on: [push]

# jobs:
#  run-shell-command:
#   runs-on: ubuntu-latest
#   steps:
#   - name: Echo a string
#     run: echo "Hello this is a first job"


name: Platform BUILD
run-name: "#${{github.run_number}} - ${{github.event.inputs.environment}}"

on:
  workflow_dispatch:
    inputs:
      Environment:
         type: choice
         description: 'select emvironment'
         options:
         - dev
         - preprod


jobs:
 run-shell-command:
  runs-on: ubuntu-latest
  steps:
  - name: Echo a string
    run: echo "Hello this is a first job"
  - name: Run a pipeleine
    run: echo "This iakanvsdvmsdlkvm s" 
  - name: Install KinD
    run: |
     curl -Lo kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
     chmod +x kind
     sudo mv kind /usr/local/bin/kind
  
  - name: Install kubectl
    run: |
     echo "Fetching latest kubectl version..."
     export KUBECTL_VERSION=$(curl -sL https://dl.k8s.io/release/stable.txt)
     echo "Using kubectl version: $KUBECTL_VERSION"
     curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
     chmod +x kubectl
     sudo mv kubectl /usr/local/bin/kubectl
    
    
